export const SET_SELECTED_BIRD = 'SET_SELECTED_BIRD'
export const SET_CORRECT_ANSWER = 'SER_CORRECT_ANSWER'
export const SET_INCORRECT_ANSWER = 'SER_INCORRECT_ANSWER'
export const SET_NEXT_LEVEL = 'SET_NEXT_LEVEL'
export const SET_NEXT_GAME = 'SET_NEXT_GAME'

